### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by smint80** [adams85/filelogger#9] opened 2020-05-05 07:09 UTC
It might be me missing something, but if there is no feature for cleaning up old files when rolling to a new file would it be posible to add that? It could be a setting of MaxFiles or something like that.

**Comment by adams85** [comment] 2020-05-06 15:16
The lib doesn't include such a feature and it's not planned, either.

Duplicate of #2

**Comment by adams85** [comment] 2020-05-06 15:17
Duplicate of #2

**Closed** 2020-05-06 15:16 UTC
Labels: duplicate
